language: node_js
node_js:
  - "5.0"
  - "4.1"
addons:
    code_climate:
        repo_token: 103972d7659b430d7bdb7a0295b12ad4040aaf238f483dcbc9ba92ca786de05d
before_install:
  - "npm install node-gyp -g"
  - "npm install eslint -g"
  - "npm install jsonlint -g"
  - "npm install istanbul -g"
  - "npm install codeclimate-test-reporter -g"
install:
  - "npm install"
  - "(cd server/ && npm install)"
  - "rm -r coverage"
script: "npm test"
after_script: "codeclimate-test-reporter < ./coverage/lcov.info"